#!/usr/bin/env python3
"""
Batch generate thinking outputs from the Omni Thinker model.
Used for building training data for the thinking summarizer model.
"""

import os
import sys
import json
import torch
import argparse
from tqdm import tqdm
from pathlib import Path
from typing import List, Dict
import re
import av

# Add project path
sys.path.insert(0, str(Path(__file__).parent.parent / "spatio-temporal-reasoner" / "src"))

from transformers import Qwen2_5OmniThinkerForConditionalGeneration, Qwen2_5OmniProcessor
from qwen_omni_utils import process_mm_info

def check_if_video_has_audio(video_path: str) -> bool:
    """Check if the video contains an audio stream"""
    try:
        container = av.open(video_path)
        audio_streams = [stream for stream in container.streams if stream.type == "audio"]
        if not audio_streams:
            return False
        return True
    except:
        return False

def extract_thinking(text: str) -> str:
    """Extract thinking part from model output"""
    think_pattern = r'<think>\s*(.*?)\s*</think>'
    matches = re.findall(think_pattern, text, re.DOTALL)
    if matches:
        return matches[0].strip()
    return ""

def extract_answer(text: str) -> str:
    """Extract answer part from model output"""
    answer_pattern = r'<answer>\s*(.*?)\s*</answer>'
    matches = re.findall(answer_pattern, text, re.DOTALL)
    if matches:
        return matches[0].strip()
    return text

def construct_message(video_path: str, question: str, problem_type: str = 'multiple choice', data_type: str = 'video') -> List[Dict]:
    """Construct model input message format (consistent with evaluation)"""
    video_audio_available = check_if_video_has_audio(video_path)
    
    # Use the original system prompt from evaluation (for training consistency)
    system_prompt = """You are a helpful assistant. Your primary goal is to deeply analyze and interpret information from available various modalities (image, video, audio, text context) to answer questions with human-like depth and a clear, traceable thought process.

Begin by thoroughly understanding the image, video, audio or other available context information, and then proceed with an in-depth analysis related to the question. 

In reasoning, It is encouraged to incorporate self-reflection and verification into your reasoning process. You are encouraged to review the image, video, audio, or other context information to ensure the answer accuracy.

Provide your understanding of the image, video, and audio between the <context> </context> tags, detail the reasoning between the <think> </think> tags, and then give your final answer between the <answer> </answer> tags."""
    
    # Add question type instruction (consistent with evaluation)
    TYPE_TEMPLATE = {
        "multiple choice": " Please provide only the single option letter (e.g., A, B, C, D, etc.) within the <answer> </answer> tags.",
        "free-form": " Please provide your text answer within the <answer> </answer> tags.",
    }
    
    question_with_instruction = question + TYPE_TEMPLATE.get(problem_type, TYPE_TEMPLATE['free-form'])
    
    if video_audio_available:
        user_content = [
            {"type": data_type, data_type: video_path},
            {"type": "audio", "audio": video_path},
            {"type": "text", "text": f"Here is a {data_type}, with the audio from the video.\n{question_with_instruction}"}
        ]
    else:
        user_content = [
            {"type": data_type, data_type: video_path},
            {"type": "text", "text": question_with_instruction}
        ]
    
    message = [
        {"role": "system", "content": [{"type": "text", "text": system_prompt}]},
        {"role": "user", "content": user_content}
    ]
    
    return message

def load_video_dataset(data_path: str) -> List[Dict]:
    """Load video dataset and extract original questions"""
    with open(data_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Adapt to different data formats
    if isinstance(data, dict):
        # WorldSense format
        videos = []
        for video_id, video_data in data.items():
            # WorldSense may have multiple tasks, each is a separate question
            for key, value in video_data.items():
                if key.startswith('task'):
                    videos.append({
                        'video_id': video_id,
                        'video_path': os.path.join(os.environ.get('DATA_ROOT', './data'), f"Videos/{video_id}/{video_id}_video.mp4"),
                        'question': value.get('question', ''),
                        'task_id': key,
                        'metadata': value
                    })
        return videos
    elif isinstance(data, list):
        # Check if already in unified format (generated by sample_datasets.py)
        if data and 'question' in data[0] and 'video_path' in data[0]:
            # Already in unified format, return directly
            return data
        
        # Daily-Omni original format
        videos = []
        for item in data:
            video_id = item.get('video_id', '')
            # Extract original questions and options
            question = item.get('Question', '')
            choices = item.get('Choice', [])
            
            # Build complete question (question + options, consistent with evaluation)
            if choices:
                full_question = question + " Options:\n"
                for choice in choices:
                    full_question += choice + "\n"
            else:
                full_question = question
            
            videos.append({
                'video_id': video_id,
                'video_path': os.path.join(os.environ.get('DATA_ROOT', './data'), f"Videos/{video_id}/{video_id}_video.mp4"),
                'question': full_question,
                'problem_type': 'multiple choice',
                'data_type': 'video',
                'metadata': item
            })
        return videos
    else:
        raise ValueError(f"Unsupported data format: {type(data)}")

def main():
    parser = argparse.ArgumentParser(description='Generate thinking outputs for training data')
    parser.add_argument('--model-path', type=str, required=True,
                        help='Path to HumanOmniV2 model checkpoint')
    parser.add_argument('--data-path', type=str, required=True,
                        help='Path to video dataset JSON')
    parser.add_argument('--output-path', type=str, default='./thinking_outputs',
                        help='Output directory for thinking data')
    parser.add_argument('--batch-size', type=int, default=1,
                        help='Batch size for inference')
    parser.add_argument('--max-samples', type=int, default=None,
                        help='Maximum number of samples to process')
    parser.add_argument('--extract-thinking-only', action='store_true',
                        help='Only extract thinking part from output')
    parser.add_argument('--shard-id', type=int, default=0,
                        help='Shard ID for multi-GPU processing (0-based)')
    parser.add_argument('--num-shards', type=int, default=1,
                        help='Total number of shards for multi-GPU processing')
    
    args = parser.parse_args()
    
    # Create output directory
    output_dir = Path(args.output_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("=" * 80)
    print("Thinking Data Generation Config")
    print("=" * 80)
    print(f"Model path: {args.model_path}")
    print(f"Data path: {args.data_path}")
    print(f"Output path: {args.output_path}")
    print(f"Using dataset original questions: yes")
    if args.num_shards > 1:
        print(f"Multi-GPU mode: Shard {args.shard_id + 1}/{args.num_shards}")
    print("=" * 80)
    
    # Load dataset
    print("\nLoading video dataset...")
    videos = load_video_dataset(args.data_path)
    
    # Data sharding (multi-GPU support)
    if args.num_shards > 1:
        total_samples = len(videos)
        shard_size = (total_samples + args.num_shards - 1) // args.num_shards
        start_idx = args.shard_id * shard_size
        end_idx = min(start_idx + shard_size, total_samples)
        videos = videos[start_idx:end_idx]
        print(f"Data shard: processing samples {start_idx}-{end_idx-1} ({len(videos)} total)")
    
    if args.max_samples:
        videos = videos[:args.max_samples]
    
    print(f"Processing {len(videos)} videos in this process")
    
    # Load model
    print("\nLoading Omni Thinker model...")
    print(f"Model path: {args.model_path}")
    
    model = Qwen2_5OmniThinkerForConditionalGeneration.from_pretrained(
        args.model_path,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="flash_attention_2"
    )
    processor = Qwen2_5OmniProcessor.from_pretrained(args.model_path)
    model.eval()
    
    print(f"Model loaded successfully")
    print(f"  Device: {model.device}")
    print(f"  Dtype: {model.dtype}")
    
    # Batch generate thinking
    print("\nStarting thinking output generation...")
    results = []
    
    for i, video_info in enumerate(tqdm(videos)):
        try:
            # Check if video file exists
            if not os.path.exists(video_info['video_path']):
                print(f"\nVideo file not found: {video_info['video_path']}")
                continue
            
            # Construct input message using the dataset's original question
            question = video_info.get('question', '')
            problem_type = video_info.get('problem_type', 'multiple choice')
            data_type = video_info.get('data_type', 'video')
            
            if not question:
                print(f"\n{video_info['video_id']} has no question, skipping")
                continue
            
            message = construct_message(video_info['video_path'], question, problem_type, data_type)
            
            # Process multimodal information
            audios, images, videos = process_mm_info(message, use_audio_in_video=False)
            
            # Apply chat template
            text = processor.apply_chat_template(
                [message],
                tokenize=False,
                add_generation_prompt=True
            )
            
            # Prepare model inputs
            model_inputs = processor(
                text=text,
                audio=audios,
                images=images,
                videos=videos,
                return_tensors="pt",
                padding=True,
                use_audio_in_video=False
            )
            
            model_inputs = model_inputs.to(model.device).to(model.dtype)
            
            # Generate output
            with torch.inference_mode():
                text_ids = model.generate(
                    **model_inputs,
                    use_audio_in_video=False,
                    max_new_tokens=2048
                )
            
            # Decode output
            input_length = model_inputs.input_ids.size(1)
            output = processor.decode(
                text_ids[0][input_length:],
                skip_special_tokens=True,
                clean_up_tokenization_spaces=False
            )
            
            # Extract thinking
            thinking = extract_thinking(output)
            answer = extract_answer(output)
            
            result = {
                'video_id': video_info['video_id'],
                'video_path': video_info['video_path'],
                'question': question,  # Keep original question
                'problem_type': problem_type,
                'thinking': thinking,
                'answer': answer if not args.extract_thinking_only else None,
                'full_output': output if not args.extract_thinking_only else None,
                'metadata': video_info.get('metadata', {})
            }
            
            results.append(result)
            
            # Periodically save
            if (i + 1) % 100 == 0:
                output_file = output_dir / f'thinking_data_batch_{i+1}.json'
                with open(output_file, 'w', encoding='utf-8') as f:
                    json.dump(results[-100:], f, ensure_ascii=False, indent=2)
                print(f"\nSaved batch data: {output_file}")
        
        except Exception as e:
            print(f"\nError processing {video_info['video_id']}: {str(e)}")
            continue
    
    # Save final results
    if args.num_shards > 1:
        output_file = output_dir / f'thinking_data_shard_{args.shard_id}.json'
    else:
        output_file = output_dir / 'thinking_data_all.json'
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    
    print("\n" + "=" * 80)
    print(f"Done! Generated {len(results)} thinking samples")
    print(f"Output file: {output_file}")
    print("=" * 80)
    
    # Statistics
    thinking_lengths = [len(r['thinking']) for r in results if r['thinking']]
    if thinking_lengths:
        print(f"\nThinking statistics:")
        print(f"  Average length: {sum(thinking_lengths) / len(thinking_lengths):.0f} chars")
        print(f"  Shortest: {min(thinking_lengths)} chars")
        print(f"  Longest: {max(thinking_lengths)} chars")

if __name__ == '__main__':
    main()
